In [1]:
import pandas as pd

In [2]:
nba_stats = pd.read_csv("../data/nba_stats.csv")

In [3]:
del nba_stats["age"]

In [4]:
# Groupby year and player 
nba_grouped = nba_stats.groupby(["year", "name", "player_id"])

In [5]:
nba_sum_grouped = nba_grouped.sum()

In [6]:
# Calculations

# average minutes
nba_sum_grouped["average_minutes"] = nba_sum_grouped["minutes_played"] / nba_sum_grouped["games_played"]
# average points 
nba_sum_grouped["average_points"] = nba_sum_grouped["points"] / nba_sum_grouped["games_played"]
# field goal percentage
nba_sum_grouped["field_goal_percentage"] = nba_sum_grouped["made_field_goals"] / nba_sum_grouped["attempted_field_goals"]
# three point percentage
nba_sum_grouped["three_point_percentage"] = nba_sum_grouped["made_three_pointers"] / nba_sum_grouped["attempted_three_pointers"]
# free throw percentage 
nba_sum_grouped["free_throw_percentage"] = nba_sum_grouped["made_free_throws"] / nba_sum_grouped["attempted_free_throws"]
# average rebounds 
nba_sum_grouped["average_rebounds"] = (nba_sum_grouped["offensive_rebounds"] + nba_sum_grouped["defensive_rebounds"]) / nba_sum_grouped["games_played"]
# average offenive rebounds
nba_sum_grouped["average_offensive_rebounds"] = nba_sum_grouped["offensive_rebounds"] / nba_sum_grouped["games_played"]
# average defensive rebounds 
nba_sum_grouped["average_defensive_rebounds"] = nba_sum_grouped["defensive_rebounds"] / nba_sum_grouped["games_played"]
# average assists
nba_sum_grouped["average_assists"] = nba_sum_grouped["assists"] / nba_sum_grouped["games_played"]
# average steals
nba_sum_grouped["average_steals"] = nba_sum_grouped["steals"] / nba_sum_grouped["games_played"]
# average blocks
nba_sum_grouped["average_blocks"] = nba_sum_grouped["blocks"] / nba_sum_grouped["games_played"]
# average turnovers 
nba_sum_grouped["average_turnovers"] = nba_sum_grouped["turnovers"] / nba_sum_grouped["games_played"]
# average personal fouls 
nba_sum_grouped["average_personal_fouls"] = nba_sum_grouped["personal_fouls"] / nba_sum_grouped["games_played"]

nba_sum_grouped.head()

                               games_played  games_started  minutes_played  \
year name           player_id
2000 A.C. Green     greenac01            82             82            1929
     A.J. Bramlett  bramlaj01             8              0              61
     Aaron McKie    mckieaa01            82             14            1952
     Aaron Williams williaa01            81              0            1545
     Adam Keefe     keefead01            62              3             604

                               points  made_field_goals  \
year name           player_id
2000 A.C. Green     greenac01     413               173
     A.J. Bramlett  bramlaj01       8                 4
     Aaron McKie    mckieaa01     653               244
     Aaron Williams williaa01     616               235
     Adam Keefe     keefead01     135                53

                               attempted_field_goals  made_three_pointeres  \
year name           player_id
2000 A.C. Green     greenac01                    387                   0.0
     A.J. Bramlett  bramlaj01                     21                   0.0
     Aaron McKie    mckieaa01                    593                   0.0
     Aaron Williams williaa01                    450                   0.0
     Adam Keefe     keefead01                    130                   0.0

                               attempted_three_pointers  made_free_throws  \
year name           player_id
2000 A.C. Green     greenac01                         4                66
     A.J. Bramlett  bramlaj01                         0                 0
     Aaron McKie    mckieaa01                       121               121
     Aaron Williams williaa01                         3               146
     Adam Keefe     keefead01                         1                29

                               attempted_free_throws  ...  \
year name           player_id                         ...
2000 A.C. Green     greenac01                     95  ...
     A.J. Bramlett  bramlaj01                      0  ...
     Aaron McKie    mckieaa01                    146  ...
     Aaron Williams williaa01                    201  ...
     Adam Keefe     keefead01                     36  ...

                               three_point_percentage  free_throw_percentage  \
year name           player_id
2000 A.C. Green     greenac01                0.250000               0.694737
     A.J. Bramlett  bramlaj01                     NaN                    NaN
     Aaron McKie    mckieaa01                0.363636               0.828767
     Aaron Williams williaa01                0.000000               0.726368
     Adam Keefe     keefead01                0.000000               0.805556

                               average_rebounds  average_offensive_rebounds  \
year name           player_id
2000 A.C. Green     greenac01          5.926829                    1.951220
     A.J. Bramlett  bramlaj01          2.750000                    1.500000
     Aaron McKie    mckieaa01          3.000000                    0.573171
     Aaron Williams williaa01          5.049383                    1.962963
     Adam Keefe     keefead01          2.193548                    0.725806

                               average_defensive_rebounds  average_assists  \
year name           player_id
2000 A.C. Green     greenac01                    3.975610         0.975610
     A.J. Bramlett  bramlaj01                    1.250000         0.000000
     Aaron McKie    mckieaa01                    2.426829         2.926829
     Aaron Williams williaa01                    3.086420         0.716049
     Adam Keefe     keefead01                    1.467742         0.548387

                               average_steals  average_blocks  \
year name           player_id
2000 A.C. Green     greenac01        0.646341        0.219512
     A.J. Bramlett  bramlaj01        0.125000        0.000000
     Aaron McKie    mckieaa01        1.317073        0.219512
     Aaron Williams williaa01        0.506173        1.135802
     Adam Keefe     keefead01        0.274194        0.209677

                               average_turnovers  average_personal_fouls
year name           player_id
2000 A.C. Green     greenac01           0.646341                1.548780
     A.J. Bramlett  bramlaj01           0.375000                1.625000
     Aaron McKie    mckieaa01           1.378049                2.365854
     Aaron Williams williaa01           0.987654                2.888889
     Adam Keefe     keefead01           0.741935                1.451613

[5 rows x 31 columns]

In [7]:
nba_sum_grouped = nba_sum_grouped.reset_index()
nba_sum_grouped

,year,name,player_id,games_played,games_started,minutes_played,points,made_field_goals,attempted_field_goals,made_three_pointeres,...,three_point_percentage,free_throw_percentage,average_rebounds,average_offensive_rebounds,average_defensive_rebounds,average_assists,average_steals,average_blocks,average_turnovers,average_personal_fouls
0,2000,A.C. Green,greenac01,82,82,1929,413,173,387,0.0,...,0.250000,0.694737,5.926829,1.951220,3.975610,0.975610,0.646341,0.219512,0.646341,1.548780
1,2000,A.J. Bramlett,bramlaj01,8,0,61,8,4,21,0.0,...,NaN,NaN,2.750000,1.500000,1.250000,0.000000,0.125000,0.000000,0.375000,1.625000
2,2000,Aaron McKie,mckieaa01,82,14,1952,653,244,593,0.0,...,0.363636,0.828767,3.000000,0.573171,2.426829,2.926829,1.317073,0.219512,1.378049,2.365854
3,2000,Aaron Williams,williaa01,81,0,1545,616,235,450,0.0,...,0.000000,0.726368,5.049383,1.962963,3.086420,0.716049,0.506173,1.135802,0.987654,2.888889
4,2000,Adam Keefe,keefead01,62,3,604,135,53,130,0.0,...,0.000000,0.805556,2.193548,0.725806,1.467742,0.548387,0.274194,0.209677,0.741935,1.451613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9308,2019,Zaza Pachulia,pachuza01,68,3,878,267,85,193,0.0,...,0.000000,0.782258,3.897059,1.455882,2.441176,1.338235,0.455882,0.250000,0.838235,2.220588
9309,2019,Zhaire Smith,smithzh01,6,2,111,40,14,34,0.0,...,0.375000,0.750000,2.166667,0.500000,1.666667,1.666667,0.333333,0.333333,1.000000,1.333333
9310,2019,Zhou Qi,qizh01,1,0,1,2,1,1,0.0,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9311,2019,Álex Abrines,abrinal01,31,2,588,165,56,157,0.0,...,0.322835,0.923077,1.548387,0.161290,1.387097,0.645161,0.548387,0.193548,0.451613,1.709677
9312,2019,Ángel Delgado,delgaan01,2,0,15,3,1,5,0.0,...,NaN,0.500000,2.000000,1.000000,1.000000,0.000000,0.500000,0.000000,0.000000,1.000000

In [8]:
# Import id_map_asg.csv
id_map_asg = pd.read_csv("../data/id_map_asg.csv")

In [9]:
# Create list of all-stars
all_stars = []

for row in id_map_asg.itertuples():
    if row[5] == 1.0:
        all_stars.append(row[3])

In [10]:
# build helper functions

def game_check(variable):
    result = []

    for x in variable:
        if x > 40:
            result.append(1)
        else:
            result.append(0)

    if sum(result) > 4:
        return True
    else:
        return False

def starter_minutes(variable):
    result = []
    
    for x in variable:
        if x >= 24:
            result.append(1)
        else: 
            result.append(0)
    
    if sum(result) > 4:
        return True
    else:
        return False
    
def role_minutes(variable):
    result = []
    
    for x in variable:
        if x < 24 and x >= 12:
            result.append(1)
        else: 
            result.append(0)
    
    if sum(result) > 2:
        return True
    else:
        return False

In [11]:
# Set up for loop to create player classification
player_id = nba_sum_grouped["player_id"]
classification = []

for player in player_id:
    player_stats = nba_sum_grouped.loc[nba_sum_grouped["player_id"] == player, :]
    games_played = player_stats["games_played"]
    games = game_check(games_played)
    minutes = player_stats["average_minutes"]
    minutes_starter = starter_minutes(minutes)
    minutes_role = role_minutes(minutes)
    
    if player in all_stars:
        classification.append("All-Star") 
    elif len(player_stats) > 4 and games == True and minutes_starter == True:
        classification.append("Starter")
    elif len(player_stats) > 2 and games == True and minutes_role == True:
        classification.append("Role Player")
    else:
        classification.append("Bust")

In [12]:
# Add Classification Column
nba_sum_grouped["classification"] = classification

In [13]:
print(nba_sum_grouped["classification"].value_counts())

Bust           3555
Starter        2434
Role Player    2400
All-Star        924
Name: classification, dtype: int64

In [14]:
nba_sum_grouped.to_csv("../data/nba_data_classified.csv", index=False)